# -*- mode: ruby -*-
# vi: set ft=ruby :

nodes = [
  { :hostname => 'ex5web', :ip => '192.168.56.210', :box => 'centos/7' },
  { :hostname => 'ex5db',  :ip => '192.168.56.211', :box => 'centos/7', :ram => 512 }
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = node[:box] ? node[:box] : "centos/7";
      nodeconfig.vm.hostname = node[:hostname] + ".box"
      nodeconfig.vm.network :private_network, ip: node[:ip], :name => 'VirtualBox Host-Only Ethernet Adapter', :adapter => 2
      memory = node[:ram] ? node[:ram] : 256;

      if Vagrant.has_plugin?("vagrant-timezone")
        config.timezone.value = "America/Sao_Paulo"
      end

      nodeconfig.vm.provider :virtualbox do |vb|
        vb.gui = false
        vb.name = node[:hostname] + ".box"
        vb.memory = memory
        vb.cpus = 1
        vb.customize [
          "modifyvm", :id,
          "--cpuexecutioncap", "50",
          "--hwvirtex", "on",
        ]
      end
    end

    #config.vm.provision :ansible do |ansible|
    #  ansible.playbook = "./provision/your_playbook.yml"
    #  ansible.inventory_file = "./provision/inventory/vagrant.py"
    #  ansible.verbose = true
    #end

    #config.ssh do |ssh|
    #  ssh.username = 'vagrant'
    #  ssh.password = 'vagrant'
    #  ssh.insert_key = false
    #end
    #config.ssh.private_key_path = "~/.ssh/id_rsa"
    config.ssh.forward_agent = true
    config.ssh.forward_x11= true
    #config.ssh.host = node[:ip]
    #config.ssh.port = 22
    #config.ssh.username = root

    config.vm.provision "shell", inline: <<-SHELL
      sudo yum makecache fast
      sudo localectl set-keymap br-abnt2
      sudo localectl set-x11-keymap br-abnt2
      sudo localectl set-locale LANG="en_US.utf8"
      sudo sed -i "s/#PermitRootLogin/PermitRootLogin/g" /etc/ssh/sshd_config
      sudo sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config
      sudo sed -i "s/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g" /etc/ssh/sshd_config
      sudo systemctl restart sshd
    SHELL
  end
end
